server:
  port: 8761     #指定服务端口
eureka:
  client:
    registerWithEureka: false  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false       #为true时，可以启动，但报异常：Cannot execute request on any known server
    service-url:
      defaultZone: http://localhost:8761/eureka/